### ISSUE TITLE
Licensed Media support

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/dmr#100]
**Note - This will require further discussion and is NOT ready for development.**

New Use Case For Licensed Media
* Need to provision a link to streaming media that can be shared via Roger record.
* Currently to get access to a DMR URL, a user needs to use SSO and have ‘admin’ privileges, otherwise they will get a 404.
* Using only SSO could be an option if we can distinguish licensed content vs. course reserves and knowing the URLs are not meant to be permanent (discuss options with IT Dev).
• Need to have file expiration date so that license expiration is automatically archived.
* User should be given a calendar and the dates need to be in YYYY-MM-DD format.

Example JSTOR monograph in Roger with UCSD IP only link (note no SSO):

![picture1](https://cloud.githubusercontent.com/assets/67506/19948312/253b5e22-a109-11e6-963a-f71d3f91c993.png)

Add button “Direct Link” to “Media Record Core Data”/ “Audio Record Core Data” page between “Play File” and “Delete” buttons and display the public URL to be used in the Roger record.

![picture2](https://cloud.githubusercontent.com/assets/67506/19948327/38cbf730-a109-11e6-852b-b69b8fca44d1.png)

**Comment by mcritchlow** [comment]
@gamontoya - Is it worth considering this as a post-launch feature to add? So far as I can tell, @VivianChu has (mostly) built all the audio requirements from the spec into DMR.

Beyond further testing, I wonder if it would benefit us to release DMR with the integrated audio functionality, which will enable us to shutdown STAR and the dependencies in DAMS3, and then continue working on this ticket after that?

**Comment by gamontoya** [comment]
@mcritchlow As discussed, the license media support requirement will be taken off the critical path for DMR release to prod. We will continue this work afterwards.

**Comment by mcritchlow** [comment]
@gamontoya sounds good 👍  In that case, I'm going to remove the STAR/DMR Merger milestone. And we can add this ticket to a future (regular) Sprint.

**Comment by mcritchlow** [comment]
This ticket is now redundant with more specific tickets for work in the queue such as #174 and #173 

Closing as a result.
