### ISSUE TITLE
Closed captioning function not working (JWPlayer)

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/dmr#102]
Kirk and I both confirm that CC is not working in any of our tested browsers:

- Chrome
- IE
- Firefox

**Comment by VivianChu** [comment]
@gamontoya I tested the video that Kirk gave me earlier http://library.ucsd.edu/dmr/media/427  and CC is working for my Firefox and IE.  It just does not work in Chrome.  Could you try that video using IE and Firefox again?  Thanks

**Comment by gamontoya** [comment]
@VivianChu Okay, I updated the to the lastest version of Flash and now CC is working on IE and Firefox.

Not working on Chrome only at this time.

**Comment by VivianChu** [comment]
@gamontoya  Could you try this video link?  http://aal.ucsd.edu/vivian.html
CC is working for me on Chrome and other browsers.  Thanks

**Comment by gamontoya** [comment]
@VivianChu CC is working for all browsers (didn't test on Safari).
