### ISSUE TITLE
JWPlayer Upgrade

### ISSUE THREAD

**Issue by VivianChu** [ucsdlib/dmr#104]
Jwplayer is recommending an upgrade in anticipation of Chrome ending flash support.
 
Here is a link from jwplayer about the coming changes.
 
https://www.jwplayer.com/blog/deprecation-flash/

**Comment by gamontoya** [comment]
Hi Gabriela and Kirk,

I deployed the change for JWPlayer in DMR to staging environment.  
Could you please test them using your browsers, iphone, and android device?

For example,

- http://librarytest.ucsd.edu/dmr/media/35
- http://librarytest.ucsd.edu/dmr/courses/49/Spring/2016/vis_101

They’re working fine for me using firefox, safari, chrome, and iphone.
 
Thanks
 
Vivian

**Comment by VivianChu** [comment]
From Kirk - This seems to work fine for me.

**Comment by gamontoya** [comment]
@VivianChu It's working for me on all browsers you noted and on my Android.

**Comment by VivianChu** [comment]
Thanks @gamontoya
