### ISSUE TITLE
Implement "Add to Course Reserve List" function for Audio Edit, Listing, and Search Results page

### ISSUE THREAD

**Issue by VivianChu** [ucsdlib/dmr#114]

**Comment by gamontoya** [comment]
@VivianChu 

Testing on staging, I created a course reserve list, added audio objects and then got a confirmation email. However, the email is missing the _Titles_ of the audio in the playlist.

`Please add a link on Ares to the playlist for Professor Lee, Jason's GAM Test CR List course for Winter 2016.
The titles in the playlist for this course are:
The path to this DMR course reserve list is:
http://librarytest.ucsd.edu/dmr/courses/53/Winter/2016/gam_test_cr_list 
Thanks!
`

**Comment by gamontoya** [comment]
Note: Vivian has not yet worked on the playlist/email functionality so this is a non-issue at this time.
