### ISSUE TITLE
Close caption not working

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/dmr#127]
Reserves staff report that cc is not working for:

- http://library.ucsd.edu/dmr/media/1821

Let's check to make sure this isn't a general issue with all videos. 

Question: does the cc button only show up once there is background noise or should it appear immediately?

**Comment by VivianChu** [comment]
@gamontoya The CC is working fine for other videos - for example - http://library.ucsd.edu/dmr/media/427  

CC button show up immediately for safari.  However for Firefox, it show up later.

**Comment by gamontoya** [comment]
@VivianChu Okay, but what about the one I reference above?

**Comment by gamontoya** [comment]
I see the cc button in Safari for /1821 but no captioning. I wonder if it is the video and not the player?

**Comment by VivianChu** [comment]
@gamontoya  CC for the one you reference above is not working.  CC for this matrix video is also working http://library.ucsd.edu/dmr/media/872  .  Do you know how the CC is created for those videos? Do they use the same tool?  Thanks

**Comment by VivianChu** [comment]
@gamontoya  http://library.ucsd.edu/dmr/media/1537  CC for that video is working automatically.  Don't need to click on CC button.

**Comment by gamontoya** [comment]
Okay, so we are suspecting the same thing. /1821 has faulty cc creation. I'll ask the creator.

**Comment by VivianChu** [comment]
@gamontoya Should we leave this ticket open until the creator re-create the video with CC?

**Comment by gamontoya** [comment]
@VivianChu We'll leave it open since I'm not sure it's the video yet. Stay tuned.

**Comment by gamontoya** [comment]
Closing this ticket for now.
