### ISSUE TITLE
Quarter should default to "None" for Audio Reserves

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/dmr#136]
**Applicable to both audio and video**
- In _create_ Course Reserve List and in Search Courses (in Archive)  Quarter should have a default to “None” instead of defaulting to Spring.

**Comment by VivianChu** [comment]
@gamontoya - This issue is the same as https://github.com/ucsdlib/dmr/issues/93
and it's done.

**Comment by gamontoya** [comment]
Duplicate of #93
