### ISSUE TITLE
Add course end date option to Course Reserve List

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/dmr#137]
**Applicable to both audio and video**
- Add course end date option so that the tool can automatically archive a Course Reserve List.
- User should be given a calendar and require that dates be in YYYY-MM-DD format.

**Comment by VivianChu** [comment]
@gamontoya - This issue is the same as https://github.com/ucsdlib/dmr/issues/99  and it's done last week.

**Comment by gamontoya** [comment]
Duplicate of #99
