### ISSUE TITLE
Document take-down checklist for STAR

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/dmr#144]
Once the Audio functionality is introduced into the production DMR application, we need to take down the STAR application and related dependences.

To Do: Please create a checklist of things that need to be taken down as it relates to STAR.

**Comment by VivianChu** [comment]
@mcritchlow - Here is a checklist of things that need to be taken down

1-star
2-xdre-star
3-solr/dar
4-star triplestore

**Comment by mcritchlow** [comment]
Great, let's leave this ticket open until all audio integration is signed off and in production. Then this will be the final ticket for the project and we can work with @ucsdlib/operations on taking those 4 things offline.

**Comment by mcritchlow** [comment]
@VivianChu I've created #148 for actually executing the take down procedure, since this ticket was just for documenting what was needed. So, feel free to close this out, and we'll handle the other ticket once we're at that point.
