### ISSUE TITLE
Update bug report feature

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/dmr#147]
Update the Bug Reporting feature to not create a ticket in JIRA. It should instead send an email to Gabriela (gamontoya@ucsd.edu). 

Also, change the report form from "Raise a Bug" to "Report a Bug".

![dmr_bug](https://cloud.githubusercontent.com/assets/4314914/23318009/9b017d46-fa85-11e6-90c5-b6c13556dc44.png)

**Comment by mcritchlow** [comment]
Glad this got caught.

Since we've moved away from using JIRA for tickets, I think we should remove this feature entirely, and look to an alternative solution.

One option could to create a Machform and embed it, as we've done for Digital Collections.

**Comment by VivianChu** [comment]
@gamontoya -  A machform has been added and deployed to pontos.  Could you take a look?  
http://pontos.ucsd.edu/dmr/

Thanks

**Comment by gamontoya** [comment]
@VivianChu Worked beautifully.
