### ISSUE TITLE
Execute take down process for STAR

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/dmr#148]
### Descriptive summary

Following the successul deployment of Audio functionality into the DMR application, we need to bring the STAR application and related services offline. This was documented in #144 

### Related work

#144

**Comment by mcritchlow** [comment]
@VivianChu - we got the green light from @gamontoya to move ahead with this. 

Please coordinate with @ucsdlib/operations as needed for this. Thanks!

**Comment by VivianChu** [comment]
@mcritchlow @gamontoya - Star has been removed from production and test environment.

**Comment by mcritchlow** [comment]
@VivianChu great! And this includes everything you listed in #144 ?

**Comment by gamontoya** [comment]
:1st_place_medal:

**Comment by VivianChu** [comment]
@mcritchlow - This only includes star, xdre-star app, apache and tomcat config files. Nobody can access production and test Star app now.  Ron and Juliana is working on removing triplestore and solr. I'll reopen the ticket and close the ticket when they're done.

**Comment by VivianChu** [comment]
@mcritchlow - Solr and Triplestore have been removed.
