### ISSUE TITLE
Remove "Quarter" option for Archive Search

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/dmr#150]
### Quarter option too confining

When in Archiving and conducting a search, remove the Quarter option entirely.

### Rationale

Kirk determined that it's too time-consuming if a user doesn't know the quarter to have to be selecting various options. It's better to have it be more like keyword.

### Notes
Vivian will look more closely at the code to make sure this change does not affect other things.

**Comment by VivianChu** [comment]
@gamontoya  - The update has been deployed to staging. Could you take a look?  Thanks

**Comment by gamontoya** [comment]
@VivianChu Looks good!
