### ISSUE TITLE
Report a bug form not working on all pages

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/dmr#152]
### Descriptive summary

Testing of the DMR module resulted in 2 fixes.

* Update the DMR Procedures and Policy link on all pages.
  * https://lisn.ucsd.edu/display/DRG/DMR+Archive+Working+Policy

* Report a bug Machform not working on the following pages _(The page you were looking for does not exist)_:
  * http://librarytest.ucsd.edu/dmr/courses/lookup
  * http://librarytest.ucsd.edu/dmr/courses/new
  * http://librarytest.ucsd.edu/dmr/audios/search?search=GAM&search_option=audio
  * http://librarytest.ucsd.edu/dmr/media/new
  * http://librarytest.ucsd.edu/dmr/audios/new

**Comment by VivianChu** [comment]
@gamontoya - The Policy link has been updated and the bug form issue has been fixed.
Could you take a look?  http://pontos.ucsd.edu/dmr
Thanks

**Comment by gamontoya** [comment]
@VivianChu Looks good Vivian.
