### ISSUE TITLE
Release DMR 2.0

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/dmr#154]
### Descriptive summary

Version: 2.0.0
Release Manager: @VivianChu 
Product Owner: @gamontoya 
Operations: @jhriv 

This release includes the work on integrating the STAR audio reserves functionality into the DMR application.

Note this should be deployed on **March 27th at the earliest** The stakeholders don't want the new application released during Finals Week.

**Comment by VivianChu** [comment]
@jhriv - The release branch has been merged into the master branch.

**Comment by gamontoya** [comment]
@jhriv This can be deployed to production now (tomorrow?).

**Comment by jhriv** [comment]
I'm getting an error from deploybot, and I can't figure out the resolution. I've asked for assistance in the deploys channel.

**Comment by jhriv** [comment]
Done. Thanks to @lsitu

**Comment by mcritchlow** [comment]
Yay! Thanks @jhriv @lsitu @VivianChu
