### ISSUE TITLE
Statistics reporting not working

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/dmr#156]
### Descriptive summary

When attempting to run analytic reports, the user is getting a **We're sorry, but something went wrong** error message. 

The issue exists for both video and audio statistics.

### Rationale

Reserves staff need to run statistics reports.

![stats](https://cloud.githubusercontent.com/assets/4314914/24519142/116e86ea-1539-11e7-954e-2a84880e4a4d.png)

**Comment by gamontoya** [comment]
@mcritchlow I created this ticket, but now I'm wondering if in the future these types of issues should because SDE tickets?

**Comment by mcritchlow** [comment]
@gamontoya yeah, it's something we should chat about. The reality is we'll end up with a ticket in GH regardless, but it is worth thinking about whether SDE should be the starting point for production bug reports. I think this is OK for now, and @VivianChu can look into it first thing on Monday.

**Comment by VivianChu** [comment]
@gamontoya - The problem has been fixed and the app has been restarted in production
![dmrstatistic](https://cloud.githubusercontent.com/assets/1864660/24720159/05b6c08a-19f1-11e7-9d2b-8c336078e121.png)
.  Could you try again? 
Attached is the screen shot.

**Comment by gamontoya** [comment]
@VivianChu Confirming that it's working. Thank you Vivian.
