### ISSUE TITLE
Release 2.0.1

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/dmr#158]
### Descriptive summary

Version: 2.0.1
Release Manager: @VivianChu 
Product Owner: @gamontoya 
Operations: @jhriv 

* Addresses Nokigiri security vulnerability via #155

**Comment by VivianChu** [comment]
@jhriv - The release branch has been merged into the master branch.  Would you please deploy it at your earliest convenient?  Thanks

**Comment by jhriv** [comment]
Done.
