### ISSUE TITLE
Release 2.0.4

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/dmr#167]
Descriptive summary

DMR Version 2.0.4
Release Manager: @VivianChu
Product Owner: @gamontoya
Operations: @jhriv

Dependency release, but would still be good to have at least one person give the app a once over.

**Comment by VivianChu** [comment]
@gamontoya - The release has been deployed to staging.  Could you please review it?  Thanks

**Comment by gamontoya** [comment]
@VivianChu Approved for production. Thanks Vivian.

**Comment by VivianChu** [comment]
@jhriv - The release has been merged into the master branch.  Could you please deploy it to prod?  Thanks

**Comment by jhriv** [comment]
Deployed to master.
