### ISSUE TITLE
Add "Report a Bug/Issue" feature to course list

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/dmr#170]
### Descriptive summary

Add option to report a bug or issue at the course list level.

### Rationale

Students and faculty should be able to instantly report a bug or an issue while in the course list view. 

### Expected behavior

- User clicks on "Report a Bug/Issue" link.
- Form has:
   - Issue Type
   - Add drop down option to select **On campus** or **Off campus**
   - Your Name
   - Your email
   - Message

### Note
Add a clickable link at the footer of the course list?

![bug](https://cloud.githubusercontent.com/assets/4314914/26169440/7efe7c54-3af2-11e7-9591-1049412a8ecc.png)

**Comment by VivianChu** [comment]
@gamontoya - The app has been deployed to pontos.  Could you take a look?

http://pontos.ucsd.edu/dmr/courses/4/edit

You can click view and the link to bug form is at the bottom.

Thanks

**Comment by gamontoya** [comment]
@VivianChu 

A few tweaks:

1. Issue Type should have the following drop down choices

![02](https://cloud.githubusercontent.com/assets/4314914/26370055/79e8ca18-3fab-11e7-9259-a946e12c2756.png)

2. Can the form send email to me (gamontoya@ucsd.edu) as well as to _reserves@ucsd.edu)_

**Comment by gamontoya** [comment]
@VivianChu 

Is there any way to make the form pull in the following information and include in the email?

- Browser
- Browser version
- Operating System

**Comment by VivianChu** [comment]
@gamontoya - Issue type drop down and the email address reserves@ucsd.edu have been added to the form.  Could you take a look?  I looked at the machform edit page and didn't see any option to pull browser info.  Maybe we could put that field in for user to enter.  What do you think?

**Comment by gamontoya** [comment]
@VivianChu Looks good Vivian. Other form builders have that option, but if MachForm does not then you'll have to ask the reporter to enter that information. After the **Campus** info. section add:

- Browser (with options below)
   - IE
   - Chrome
   - Firefox
   - Safari
   - Opera

- Browser version (must enter)

- Operating System (must enter)

**Comment by VivianChu** [comment]
@gamontoya - The browser section has been added to the form.  Could you take a look?  Thanks

**Comment by VivianChu** [comment]
@gamontoya - I'll try to write some custom javascript to load the browser info into the form and will let you know when it's ready to review.

**Comment by VivianChu** [comment]
@gamontoya -The browser info is captured automatically when user submit the form now. 
For example, the email will have this field 
User Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:51.0) Gecko/20100101 Firefox/51.0
Could you take a look?  Thanks

**Comment by gamontoya** [comment]
@VivianChu Perfect. This is great Vivian!

**Comment by gamontoya** [comment]
@VivianChu Actually, I see this:

Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

Should it not report Windows 7 and Chrome for me and not that string above?

**Comment by gamontoya** [comment]
@VivianChu Also, reCaptcha is not working with Chrome. Note that it works with IE. Does it work with Safari?

**Comment by gamontoya** [comment]
This is the user agent info. I get from Firefox:

Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; InfoPath.3; Zoom 3.6.0; rv:11.0) like Gecko

**Comment by VivianChu** [comment]
@gamontoya - Captcha is working fine for my version of Chrome and Safari. User agent should returns the value of the user-agent header sent by the browser to the server.
The value returned, contains information about the name, version and platform of the browser.
Could you try this page to see your firefox and chrome user agent is the same as the matchform?

https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_nav_all

The string you see for chrome - Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36  already mentions Chrome/58.0.3029 and Window platform

**Comment by gamontoya** [comment]
@VivianChu We should be okay, but for platform I was expecting to see Windows 7 or Windows XP, etc.

**Comment by VivianChu** [comment]
@gamontoya : What value did you see for your platform from this link https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_nav_all   For me, I got this Platform: MacIntel   .  I can add one more field OS/Platform into the machform.

**Comment by gamontoya** [comment]
I got **Platform: Win32** - Maybe just add the Platform?

**Comment by VivianChu** [comment]
@gamontoya - I added that field in under the label OS.  From the email it will be like this - OS	MacIntel
Could you try again?

**Comment by gamontoya** [comment]
@VivianChu I think we're good to go now, Vivian. Thank you for your patience.

**Comment by VivianChu** [comment]
Thanks @gamontoya for testing.  I'll close this ticket.
