### ISSUE TITLE
Licensed Media - Add direct link/URL

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/dmr#173]
### Descriptive summary

Add button “Direct Link” (or URL) to “Media Record Core Data”/ “Audio Record Core Data” page between “Play File” and “Delete” buttons.

Vivian can recommend the appropriate URL derivation convention.

### Rationale

New Use Case For Licensed Media: need to provision a URL to streaming media that can be shared via Roger record (856).

### Expected behavior

When a user clicks on the “Direct Link” button, the link to the streaming audio/video is displayed in a new box below File Name.

![direct](https://cloud.githubusercontent.com/assets/4314914/26377010/6bfcbb90-3fc3-11e7-950c-5ad36e1e47f6.png)

**Comment by mcritchlow** [comment]
Nice job @VivianChu 👍

**Comment by gamontoya** [comment]
Yes, great work!
