### ISSUE TITLE
Tighten security restrictions at the class level (URL)

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/dmr#176]
### Descriptive summary

Vivian to work with Justin to figure out the best way to lock down media/class level URLs

ITS can get the feeds from campus 4 times a day with updated patron information (who is in what class). Put this in a MS SQL database? Vivian can figure out how to connect to it the database.

### Rationale

Currently, students can share a media URL with anyone. We do not want this behavior.

**Comment by gamontoya** [comment]
@VivianChu Will this be worked on in this Sprint or the next?

**Comment by VivianChu** [comment]
@gamontoya - I'm still working on this for this Sprint.

**Comment by VivianChu** [comment]
@gamontoya - Access control has been added to the course report url. The change is deployed to pontos.  For example
http://pontos.ucsd.edu/dmr/courses/4/Spring/2016/test_course_01_21_16_222

If user is not in course , he/she will see this screen.
![dmrforbiddenmessage](https://user-images.githubusercontent.com/1864660/27245104-8ff71124-529e-11e7-812f-c40499eb5125.png)

**Comment by gamontoya** [comment]
@VivianChu Excellent!

**Comment by gamontoya** [comment]
@VivianChu Do we need an "admin" role? That is, will I be able to access the URL as well as reserves staff?
