### ISSUE TITLE
Add sorting capability to columns in course list

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/dmr#196]
### Descriptive summary

Reserves staff would like to be able to sort the content/columns in a course list in **ascending** and **descending** order.

### Rationale

Reserves staff state that it would be helpful when the instructor wants a large portion of an album and wants it in order. Their work would be much faster if they could sort by file names. Given this need it would make sense to make all columns (with the exception of No.) sortable.

**Note:** "No." column should not be sortable.

### Example

![dmr audio1](https://user-images.githubusercontent.com/4314914/32116315-fdbdd800-bafe-11e7-9a9b-18888cb2aa69.png)

**Comment by gamontoya** [comment]
@mcritchlow Not sure if Vivian has the bandwidth to do this in this coming Sprint?

**Comment by mcritchlow** [comment]
@gamontoya - yeah i think so, though she's only in for half the Sprint. So perhaps at least a start on this.
