### ISSUE TITLE
Make sorting alpha numeric instead of by string

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/dmr#201]
### Descriptive summary

The sorting function is not working as reserves staff expected. 

Getting 1, 10, 2, 3, 4, 5 instead of **1, 2, 3, 4, 5...10**

### Related work

#197

**Comment by gamontoya** [comment]
Make sure it works for the file naming column too. Today I saw:

MUD33814_1_1.mp3
MUD33814_1_10.mp3
MUD33814_1_11.mp3
MUD33814_1_2.mp3

**Comment by VivianChu** [comment]
@gamontoya - Which environment did you try?  This change is only get deployed to pontos.  Attached is the screen shot for filename sorting.  
![filenamesorting](https://user-images.githubusercontent.com/1864660/33032940-9c140958-cdd7-11e7-8cbb-1be921d1d288.png)
