### ISSUE TITLE
Issue with video viewing

### ISSUE THREAD

**Issue by VivianChu** [ucsdlib/dmr#243]
### Descriptive summary

Subject: Report A Bug [#47]
 
User Agent
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
Issue Type
Reporting a problem
Off Campus
Name
Cassey Lau
Email
cal093@ucsd.edu
Message
Currently I am trying to access my online course reserves, however there is a repetitive error that says the films "Cannot load M3U8: Crossdomain access denied." I have not received this issue while using course reserves off campus and nor have I logged in with any other computer or window.
OS
MacIntel

**Comment by gamontoya** [comment]
----Original Message-----
From: Cassey Lau [mailto:cal093@ucsd.edu] 
Sent: Tuesday, February 06, 2018 9:40 AM
To: Montoya, Gabriela <gamontoya@ucsd.edu>
Subject: RE: Report A Bug [#47]

Hello,

I am not using a VPN, yesterday I also tried to using the UCSD VPN; however I was lead to the same problem. Currently I am using google chrome to view.
The course is LTEA 138 and it is all the videos within the course
(https://library.ucsd.edu/dmr/courses/743/Winter/2018/ltea_138 ). The professor has also stated that we should be able to watch the films off campus and I have been able to up until yesterday.
As an update, I checked again on campus and I am able to view the films, but again the inconvience of this is troublesome when the films should be viewable off campus.
Thank you so much for your time, I look forward to hearing back soon.

With Regards,
Cassey Lau
