### ISSUE TITLE
Test Securetoken in DMR

### ISSUE THREAD

**Issue by tmarconi** [ucsdlib/dmr#263]
### Descriptive summary

SecureToken from Wowza isn't working correctly currently, we would like to see if it can be implemented in a test version of DMR (or DAMS) to see if anything breaks.  Any questions, you can work with @rstanonik 

### Rationale

Below is the php I’m using to generate the URLs (playlist.m3u8 and manifest.mpd) for my securetoken test.

The end time can easily be changed to 48 hours as Tim said Declan suggested.

And, although, I'm not using it, the client IP can also be included, so that only that IP can open the stream.

Finally, here is some documentation.

https://www.wowza.com/docs/how-to-protect-streaming-using-securetoken-in-wowza-streaming-engine

https://www.wowza.com/community/questions/7933/secure-token-not-being-able-to-make-it-work.html

<?php
  $host = "lib-streaming.ucsd.edu";
  $url= "https://".$host.":1936/";
  $stream = "dams4-securetoken/_definst_/bb/87/38/33/5h/20775-bb8738335h-0-2.mp4
";
  date_default_timezone_set('America/Los_Angeles');
  $end = strtotime("+5 minutes"); // token will expire in 5 minutes
  $secret = "XXX"; // secret as defined in Engine
  $tokenName = "wowzatoken"; // token prefix as defined in Engine
  $hash = hash('sha256', $stream."?".$secret."&{$tokenName}endtime=".$end, true) ;
  $base64Hash = strtr(base64_encode($hash), '+/', '-_');
  $params = array("{$tokenName}endtime=".$end,"{$tokenName}hash=".$base64Hash);
  sort($params);

  $URL = $url.$stream."/playlist.m3u8?";
  $playbackURL = $URL;
  foreach($params as $entry){
    $playbackURL.= $entry."&";
  }
  $URL = preg_replace("/(\&)$/","", $playbackURL);

  $URLmpd = $url.$stream."/manifest.mpd?";
  $playbackURLmpd = $URLmpd;
  foreach($params as $entry){
    $playbackURLmpd.= $entry."&";
  }
  $URLmpd = preg_replace("/(\&)$/","", $playbackURLmpd); ?>

**Comment by rstanonik** [comment]
I created working php examples for dams and dmr in a place that Vivian can access to see working code so she can figure out how to do it in ruby/rails.

https://aal.ucsd.edu/tchu/dams4-securetoken/

https://aal.ucsd.edu/tchu/dmr-securetoken/

**Comment by VivianChu** [comment]
@jhriv - Could you deploy the new DMR environment variables to Staging environment?  It's working fine on pontos.  Thanks
