### ISSUE TITLE
Test JWPlayer 8 (R&D only)

### ISSUE THREAD

**Issue by VivianChu** [ucsdlib/dmr#290]
### Descriptive summary

Upgrade to JWPlayer 8 and test it a test environment. Some of the changes include:

- JWPlayer is loaded from the cloud
- The playlist is an icon in the bottom right

Example - https://library.ucsd.edu/jwplayer-cloud/

**Comment by gamontoya** [comment]
On hold until Gabriela talks to Tim.

**Comment by gamontoya** [comment]
@VivianChu Per Tim, instructions are to try this out in a test environment and make sure it actually works. We are not to upgrade DMR or DAMS to this version at this time. This is only R&D.

**Comment by VivianChu** [comment]
@gamontoya - Should I use the new playlist icon or try to create the old playlist with this upgrade?  Thanks

**Comment by gamontoya** [comment]
@VivianChu If the level of effort to create the old playlist view isn't too high, I'd give reserves folks that view too.

So the deliverable would a view of JWPlayer 8:

- with a playlist as is
- with a playlist to look like the old playlist
- with a view for a DAMS video object.

Once you've done that, I'll send to DMR reserves staff for review (not the DAMS object view).

How does that sound?

**Comment by VivianChu** [comment]
@gamontoya - Sounds good. Thanks

**Comment by VivianChu** [comment]
@gamontoya - The update has been deployed to staging.  Could you review it?  Thanks
For example 

//video playlist

https://librarytest.ucsd.edu/dmr/courses/103/edit

//single video obj
https://librarytest.ucsd.edu/dmr/media/48

//audio playlist
https://librarytest.ucsd.edu/dmr/courses/105/Fall/2018/test_jwplayer8_audio_playlist

//single audio obj
https://librarytest.ucsd.edu/dmr/audios/49

**Comment by gamontoya** [comment]
@VivianChu They play, yes. What am I supposed to be looking for?

**Comment by VivianChu** [comment]
@gamontoya - The new playlist icon and to see if they play fine.

**Comment by VivianChu** [comment]
@gamontoya - Could you also ask DMR reserves staff to see if they like the new playlist icon and it's ok to remove the old playlist style? Thanks

**Comment by gamontoya** [comment]
@VivianChu Can you share a screenshot of the playlist icon you see?

**Comment by VivianChu** [comment]
@gamontoya - After clicking the playlist icon, here's what I see
![videoplaylisticon](https://user-images.githubusercontent.com/1864660/44363690-bfc29a80-a479-11e8-8c7b-9a6d79a7170f.png)

**Comment by VivianChu** [comment]
@gamontoya - Sometime I see the playlist doesn’t show the video list at the bottom.  When I reload the page, then the video list is there.  Do you see that problem?

**Comment by gamontoya** [comment]
@VivianChu Same thing happens to me. Is there a fix?

**Comment by VivianChu** [comment]
@gamontoya - I'll try to replicate the problem for my local env and will try to fix it.  I'll keep you posted.  Thanks
