### ISSUE TITLE
Capture course list URL when reporting problem via MachForm

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/dmr#317]
### Descriptive summary

When a user reports an issue/problem using the MachForm in a course list, it does not capture the course or video. 

It would be very helpful to troubleshoot issues quicker if the course information is captured by the MachForm.  Note that capturing part of the URL shown below in red might be the best thing to capture.

![machform](https://user-images.githubusercontent.com/4314914/47668309-50e27b80-db65-11e8-8a85-4e098727aba4.png)

**Comment by VivianChu** [comment]
@gamontoya - The form has been updated to capture the course list url.  Here's the screen shot of the email after the update.
![machform2](https://user-images.githubusercontent.com/1864660/47941688-6f6dad00-deac-11e8-850b-bee401ba9501.png)

**Comment by gamontoya** [comment]
@VivianChu Yay! Very nice, Vivian.
