### ISSUE TITLE
Statistics throwing "something went wrong" error message

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/dmr#360]
### Descriptive summary

When running a report for statistics in DMR, get `We're sorry, something went wrong` regardless of the date range used.

![stats](https://user-images.githubusercontent.com/4314914/55099438-e898b700-507c-11e9-854b-f776fea56ad4.png)

**Comment by gamontoya** [comment]
@VivianChu Any updates on this?

**Comment by VivianChu** [comment]
@gamontoya - I haven't heard anything from Ron or Tim yet. I'll check with them again and keep you posted.  
@rstanonik -  Have you heard anything from Tim about the splunk license?  Thanks

**Comment by VivianChu** [comment]
@gamontoya -  The problem has been fixed in production.  Could you try again?  Thanks

**Comment by gamontoya** [comment]
@VivianChu Looks good. Thank you.

**Comment by gamontoya** [comment]
> Hi Gabriela,  After Ron increased the quota, restarted splunk and restarted tomcat on staging, statistic worked again.  It took about 8 min for that range - 01/06/2019 - 03/30/2019.  I just asked him to restart tomcat on production early morning next monday.  When he’s done, I’ll try and will keep you posted.  He told me that he did upgraded splunk before.  Probably the upgrade affect the quota and cause the problem.

@VivianChu To ping Gabriela on Slack when Tomcat is restarted.

**Comment by VivianChu** [comment]
@VivianChu - The server has been restarted.  It worked fine for me.  Here's the screen shot.  For video stas, it took about 15 min.  For audio stats, it took about 4 min with the same date range 01/06/2019 - 03/30/2019.  Could you review it? Thanks
![videoStats](https://user-images.githubusercontent.com/1864660/56150994-0b740800-5f65-11e9-8687-d6b64affede8.png)

**Comment by gamontoya** [comment]
It takes awhile, but it works.
