### ISSUE TITLE
Improve Playlist feature (icon)

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/dmr#365]
### Descriptive summary

It's hard to find the playlist when not in full screen mode.

To do in the Staging environment:
1. Remove our custom design playlist since the latest JWPlayer does not support it. Remove it and default to using the JWPlayer design.
2. Keep the custom design playlist and update the thumbnail size.

### Rationale

NAME:     Aaron Lagman
PHONE:    619-677-8798
E-MAIL:   jalagman@ucsd.edu
USEFUL:   Partially
ISSUE:   null
COMMENT:  The options for the other videos for the course take up too much space when I am viewing a video. Please fix this.

**Comment by VivianChu** [comment]
@gamontoya - I deployed the version that remove the custom playlist section to staging.  Could you review it?  
https://librarytest.ucsd.edu/dmr/courses/108/Fall/2018/test_video_list_3_9_21_2018
I'll be working on #2 next, update the thumbnail sizes. 

Thanks

**Comment by VivianChu** [comment]
@gamontoya - The version with responsive playlist has been deployed to staging.  Could you review it?  Thanks
