### ISSUE TITLE
Remove NewRelic and add honeycomb

### ISSUE THREAD

**Issue by VivianChu** [ucsdlib/dmr#375]

**Comment by mcritchlow** [comment]
So the steps are:
1. Create datasets in Honeycomb (DONE)
2. Get `env-variables` setup for honeycomb in DMR
3. Add gem, env vars, and config snippet to DMR

I should be able to do 2,3 tomorrow @VivianChu. Does that work?

**Comment by VivianChu** [comment]
@mcritchlow - sounds good.  Thanks.
