### ISSUE TITLE
UCSD-GUEST network users cannot connect to streaming video/audio service on ports TCP 1935 and 1936

### ISSUE THREAD

**Issue by VivianChu** [ucsdlib/dmr#405]
### Descriptive summary

UCSD-GUEST network users cannot connect to the Geisel Library streaming video/audio service on ports TCP 1935 and 1936.  These ports are accessible to UCSD-PRIVATE and even to off campus, but not to UCSD-GUEST users.
There two servers: lib-streaming.ucsd.edu (132.239.119.181) and lib-streaming-test.ucsd.edu (132.239.119.176), which provide streaming service on two ports, which should be accessible to anyone on campus of off (TCP 1935 and 1936).

**Comment by VivianChu** [comment]
@gamontoya - Ron made some change to the streaming server.  I updated DMR and deployed it to staging.  Could you try to see if they work for you using UCSD-Guest wireless network? Thanks
For example
Video playlist - https://librarytest.ucsd.edu/dmr/courses/111/Fall/2018/test_video_course_1_-_09_24_2018
Audio playlist -  https://librarytest.ucsd.edu/dmr/courses/109/Fall/2018/test_audio_list_2_09_21_2018

**Comment by gamontoya** [comment]
@VivianChu I don't think I can access from UCSD-Guest wireless from home.

**Comment by VivianChu** [comment]
@VivianChu - You can try whenever you're on campus.  I also can't access UCSD-Guest wirefless from home.  I'll test them next week when I'm on campus.  Those videos/audios worked for Ron on UCSD-Guest wireless.

**Comment by gamontoya** [comment]
@VivianChu Thanks. I'll test when I'm on campus too...on Tuesday.

**Comment by gamontoya** [comment]
@VivianChu By the way, this did work using UCSD-guest, but it made me use SSO for each link. If that is expected behavior, then it's all good!

**Comment by VivianChu** [comment]
@gamontoya - DMR users always need to login in order to watch video.  That is expected behavior.
