### ISSUE TITLE
"views" on the Video Analytics Overview is not show the view count

### ISSUE THREAD

**Issue by VivianChu** [ucsdlib/dmr#413]
https://ucsdlibrary.zendesk.com/agent/tickets/447

**Comment by VivianChu** [comment]
@gamontoya - The problem has been fixed and deployed to staging.  Could you review it?  Thanks

Here are the screen shots.

//Before the fix
![beforeViewCountFixVideo](https://user-images.githubusercontent.com/1864660/71926481-4a2b9d00-3148-11ea-8b6c-513aac3e3f7f.png)
![beforeViewCountFixAudio](https://user-images.githubusercontent.com/1864660/71926502-531c6e80-3148-11ea-98ec-f85de582e35f.png)

//After the fix
![afterViewCountFixVideo](https://user-images.githubusercontent.com/1864660/71926507-57e12280-3148-11ea-83c6-b547e8519ed1.png)
![afterViewCountFixAudio](https://user-images.githubusercontent.com/1864660/71926515-5b74a980-3148-11ea-8ffd-f416ee68193b.png)

**Comment by gamontoya** [comment]
@VivianChu Hi Vivian. I got the correct output on DMR stage. Do you need a release ticket?

**Comment by VivianChu** [comment]
@gamontoya - Thanks for reviewing.  Yes, I need a release ticket.
