### ISSUE TITLE
Accessibility Checker should check more than the landing page

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/dmr#85]
Currently it appears that the accessibility checker is crawling the landing page only. Please determine if either of the following are possible:

- A list of URL's can be provided to check (might be more performant)
- A recursive crawl can be done for the entire application

**Comment by VivianChu** [comment]
@mcritchlow I updated the seeds to populate data into development environment and added a list of URL to check.  The course report url works fine too.

**Comment by mcritchlow** [comment]
@VivianChu - great! Can you compile a list of those core accessibility issues for your test course (accesslint-ci scan http://localhost:3000/courses/1/Spring/2015/test_course_1) and search results? I think a ticket for addressing those would be a good next step since you have the tool working well now. At a quick glance, it seemed that many of the issues might be able to be addressed in the global templates. Hopefully :)
