### ISSUE TITLE
Course Reserve List enhancement

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/dmr#93]
In Course Reserve List, Quarter should have a default to “none” instead of defaulting to Spring.  Reorder quarters to be Fall, Winter, Spring, Summer.

![picture1](https://cloud.githubusercontent.com/assets/67506/19948041/f0db9a1c-a107-11e6-81d6-ebb8b1f691c5.png)

**Comment by VivianChu** [comment]
@gamontoya - Quarter is a required field.  It should have a default to some quarter.  What do you think?  Thanks

**Comment by gamontoya** [comment]
@VivianChu Yes so it should default to "Fall".
